# Generated by Django 4.1.6 on 2023-02-07 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=65)),
                ('descricao', models.CharField(max_length=165)),
                ('slug', models.SlugField()),
                ('prep_time', models.IntegerField()),
                ('prep_time_unit', models.IntegerField()),
                ('servings', models.IntegerField()),
                ('servings_unit', models.CharField(max_length=65)),
                ('prep_steps', models.TextField()),
                ('prep_steps_is_html', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('publicado', models.BooleanField(default=False)),
                ('cover', models.ImageField(upload_to='receitas/cover/%Y/%m/%d/')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='receitas.categoria')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
